FROM ubuntu:latest
LABEL maintainer="Ramon Martins <ramonmartins.campos@gmail.com>"
LABEL description="Exemplo de instalação com Dockerfile ."

RUN echo "nameserver 8.8.8.8" | tee /etc/resolv.conf > /dev/null &&\
apt-get update && \
apt-get install python 


EXPOSE 80/tcp